### ISSUE TITLE
Error coming while installation

### ISSUE THREAD

**Issue by StaRKCrypto** [bhwsite/apecoin-claim-checker#1]
PS C:\Users\darks\Desktop\apecoin-claim-checker-main> npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for colourize@^1.4.45.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\darks\AppData\Local\npm-cache\_logs\2022-06-03T15_02_32_415Z-debug-0.log

**Comment by StaRKCrypto** [comment]
![image](https://user-images.githubusercontent.com/106826001/171881661-c7a74400-cc76-449b-af92-cff6aa2da724.png)

**Comment by bhwsite** [comment]
Thanks for letting me know. I just updated the repo and it should be working now. I'm closing this issue since it's resolved. If error still persist feel free to re-open
